### ISSUE TITLE
macro psr

### ISSUE THREAD

**Issue by HengYongChao** [kimata/esp32_ulp_sht3x#1]
`.macro psr
    .set Lret_addr,(.+16)
    move r1,Lret_addr
    push r1
.endm`

How to understand (.+16)? which means the pc local address + 16 ? and then save the offset address to stack? @kimata

**Comment by HengYongChao** [comment]
And Why +16? why chose this value?

**Comment by kimata** [comment]
Good question.

psr
jump XXX 

is expanded to

    move r1,Lret_addr
    st r1,r3,0
    sub r3,r3,1
    jump XXX

So, the return address is current address + 4 words.
1word is 32bit = 4byte, and the offset address is 4 * 4 = 16.

**Comment by HengYongChao** [comment]
@kimata  Thanks！

**Comment by HengYongChao** [comment]
Hi, @kimata. Sorry, I'm a newbie and I have other question.
`.macro pop rx
    add r3,r3,1
    ld \rx,r3,0
.endm`
Why pop or push operate the stack pointer move one step, but psr operate the stack pointer move four steps?

**Comment by kimata** [comment]
The code below is storing return address, not manipulating stack pointer. 

move r1,Lret_addr
push r1
